server:
  port: 7300

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.201:7010/eureka/

api:
#  host: http://192.168.31.201:7020
  host: http://localhost:7020



# 数据库连接
jdbc: 
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.31.113:3306/trip_manage?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: qianying
  testSql: SELECT 1
