server:
  port: 8980

api:
  host: http://192.168.31.198:6020



# 数据库连接
jdbc: 
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.31.198:3306/trip_manage?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: Qianying123!@#
  testSql: SELECT 1
